### ISSUE TITLE
How can i create extension for a plugin?

### ISSUE THREAD

**Issue by umakantsharmacedcoss** [artf/grapesjs-plugin-boilerplate#1]
Hello,

I'm exploring it and a newbie, Apologies if the question is silly!

I want to create an extension for newsletter preset https://github.com/artf/grapesjs-preset-newsletter/blob/master/src/blocks.js!

With the help of this plugin boilerplate how can i do the same?

Thanks!

**Comment by umakantsharmacedcoss** [comment]
For now what i am doing is, i created a separate plugin as i have to extend some block componenet's, and build that using as a plugin dependency, but if there is any way i can make it like an extension and only have to add my script, so that in case of any update of preset-newsletter plugin, my plugin will not break!

**Comment by artf** [comment]
Well if you create an **extension** of something, that means, somehow, you rely on its underlying structure. So if you need to extend some block just make sure they exist
